### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [git-hulk/tcpkit#19]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [server_init](https://github.com/git-hulk/tcpkit/blob/d98ac021b2f9e4de2e1b7858d28ba6c86a81728e/src/server.c#L39)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [parse_options](https://github.com/git-hulk/tcpkit/blob/f1539be2e8646ab880ffac3bde3c2febc07f48a6/src/tcpkit.c#L96)

**Comment by git-hulk** [comment]
yeah, pr is welcome

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to [detect every error situation](https://github.com/git-hulk/tcpkit/blob/25c1340c0391b6cb09f902cb9b2cac53075982f6/src/server.c#L218 "Update candidate: server_create_stats_thread()") as early as possible?
