### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [git-hulk/tcpkit#20]
The function “[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[signal_handler](https://github.com/git-hulk/tcpkit/blob/f1539be2e8646ab880ffac3bde3c2febc07f48a6/src/tcpkit.c#L41 "Update candidate")”.

**Comment by git-hulk** [comment]
it makes sense, but it would be safe while the tcpkit would never get back to execute after entering the signal

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)
