### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [git-hulk/tcpkit#21]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [empty_unit_iface](https://github.com/git-hulk/tcpkit/blob/50249105b25200662515396e4f7bba41929173aa/deps/libpcap/pcap-sita.c#L192 "empty_unit_iface function")
- [server_deinit](https://github.com/git-hulk/tcpkit/blob/d98ac021b2f9e4de2e1b7858d28ba6c86a81728e/src/server.c#L77 "server_deinit function")

**Comment by git-hulk** [comment]
@elfring thanks for your advice, I would check it

**Comment by git-hulk** [comment]
It's unnecessary to check the null point when free, I would remove those later, or pr is welcome.
