### ISSUE TITLE
I can't run normally

### ISSUE THREAD

**Issue by phillip2019** [git-hulk/tcpkit#3]
I can't run normally, it shall be reported to the error
![image](https://cloud.githubusercontent.com/assets/5674071/20425089/f5149724-adb3-11e6-887f-ae18b76921e0.png)

**Comment by git-hulk** [comment]
@songxiaowei112 

which platform? centos, debian, or .... can you offer more information about the error.

``` shell
 46 deps: nop
 47     @cd ../deps/libpcap/  && ./configure && make
 48     @cd ../deps/lua/src && make $(os_Platform)
```

it seems command 'cd' didn't work in Makefile, so it can't find the configure file

**Comment by phillip2019** [comment]
Red hat 6.5

**Comment by git-hulk** [comment]
@songxiaowei112 the `/bin/sh` is missing, link or copy sh script to /bin/sh
